<?php
/**
 * TL_ROOT/system/modules/realurl/languages/ja/default.php 
 * 
 * Contao extension: realurl 1.0.0 rc2 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2012 MEN AT WORK 
 * License   : LGPL 
 * Author    : Andreas Isaak (menatwork), http://www.men-at-work.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['ERR']['realurl'] = "\"%s\"というキーワードは機能拡張が使用するため使用できません。<br />禁止のキーワード: %s";
$GLOBALS['TL_LANG']['ERR']['aliasExistsFolder'] = "\"%s\"というエイリアスは既に存在します!  (親のエイリアスを自動的に追加します。)";
$GLOBALS['TL_LANG']['ERR']['noRootPageFound'] = "適切なウェブサイトのルートがありません。";
$GLOBALS['TL_LANG']['ERR']['realUrlKeywords'] = "エイリアスにキーワードとして予約している単語が含まれています。";
$GLOBALS['TL_LANG']['ERR']['realUrlKeywordsExt'] = "以下のページのエイリアスはキーワードとして予約している単語を含んでいます。<a href=\"%s\">%s (ID: %s)</a> キーワード: %s";
$GLOBALS['TL_LANG']['ERR']['emptyRealUrlOverwrite'] = "完全なエイリアスは空にできません。";
 
?>
