<?php
/**
 * TL_ROOT/system/modules/realurl/languages/ja/tl_page.php 
 * 
 * Contao extension: realurl 1.0.0 rc2 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2012 MEN AT WORK 
 * License   : LGPL 
 * Author    : Andreas Isaak (menatwork), http://www.men-at-work.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['realurl_legend'] = "エイリアスの設定";
$GLOBALS['TL_LANG']['tl_page']['folderAlias']['0'] = "フォルダーのエイリアスを生成";
$GLOBALS['TL_LANG']['tl_page']['folderAlias']['1'] = "(フォルダーのような)親のエイリアスを含んだページのエイリアスを生成したい場合に選択してください。";
$GLOBALS['TL_LANG']['tl_page']['subAlias']['0'] = "下位のページのエイリアスを生成";
$GLOBALS['TL_LANG']['tl_page']['subAlias']['1'] = "すべての下位のページのエイリアスを生成";
$GLOBALS['TL_LANG']['tl_page']['useRootAlias']['0'] = "ウェブサイトのルートのエイリアスを使用";
$GLOBALS['TL_LANG']['tl_page']['useRootAlias']['1'] = "すべての他のページの基準にウェブサイトのルートのエイリアスを使用します。";
$GLOBALS['TL_LANG']['tl_page']['realurl_overwrite']['0'] = "ページのエイリアスを上書き";
$GLOBALS['TL_LANG']['tl_page']['realurl_overwrite']['1'] = "クリックすると全体のエイリアスをリセットします。";
 
?>
