<?php
/**
 * TL_ROOT/system/modules/realurl/languages/ja/tl_settings.php 
 * 
 * Contao extension: realurl 1.0.0 rc2 
 * Japanese translation file 
 * 
 * Copyright : &copy; 2012 MEN AT WORK 
 * License   : LGPL 
 * Author    : Andreas Isaak (menatwork), http://www.men-at-work.de 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_settings']['urlKeywords']['0'] = "URLのキーワード";
$GLOBALS['TL_LANG']['tl_settings']['urlKeywords']['1'] = "RealURL機能拡張が変数と見なさなければならない追加のキーワードを(コンマで区切って)入力してください。";
 
?>
